# Aufgaben zur Analyse von Verkehrsmengen

Für die Bewertung der bestehenden und für die Planung der zukünftigen Straßenverkehrsinfrastruktur werden Informationen über das aktuelle sowie Prognosen für das zukünftige Verkehrsaufkommen benötigt. Auf Autobahnen und Bundesstraßen unterhält die Bundesanstalt für Straßen- und Verkehrswesen (BASt) dazu Dauerzählstellen. Die gewonnenen Daten sowie die Beschreibung der Daten werden auch online auf der Seite der BASt zur Verfügung gestellt.

::: {#exr-karte-verkehr-bab}

## Deutschlandkarte mit Zählstellendaten

Erstellen Sie eine Karte des deutschen Autobahnnetzes und stellen Sie in dieser Karte die Verkehrsbelastungen für ein beliebiges Jahr dar.
:::

::: {#exr-ganglinien}
## Vergleich von Verkehrsmengen auf Bundesautobahnen

Wählen Sie zwei Zählstellen von Autobahnen in einem Ballungsraum und zwei weitere Zählstellen von Autobahnen außerhalb eines Ballungsraumes. Führen Sie folgende Auswertungen durch:

a) Erstellen Sie für eine ausgewählte Zählstelle eine Ganglinie für jeden Wochentag und stellen Sie diese in einem Diagramm dar.

b) Bestimmen Sie die mittlere werktägliche Verkehrsbelastung (mittlere Stundenwerte dienstags bis
donnerstags, ohne Feiertage und außerhalb der Schulferien) und stellen Sie die Ganglinien eines mittleren Werktages für alle Zählstelle in einem Diagramm dar. 
Erstellen Sie mit denselben Filtern (ohne Feiertage und außerhalb der Schulferien) für alle Zählstelle ein Diagramm für Samstage und Sonntage.

c) Bestimmen Sie für eine der vier Zählstellen die Verkehrsstärke der 50. höchst belasteten Stunde des Jahres und geben das Ergebnis in einer Tabelle aus. Wählen Sie zudem eine geeignete Darstellungsform, um die 50. Stunde im Vergleich zu den restlichen Stunden eines Jahres auszugeben.

d) Untersuchen Sie den prozentualen Anteil des Schwerverkehrs in der Zeitspanne 2003 bis 2023 auf deutschen Autobahnen.
Welche Entwicklung / Tendenz lässt sich erkennen?
:::


