---
title: "Aufgaben zur Analyse von Verkehrsmengen"
format: 
  html:
    toc: true
    number-sections: true
    colorlinks: true
---

Für die Bewertung der bestehenden und die Planung der zukünftigen Straßenverkehrsinfrastruktur werden Informationen über das aktuelle sowie Prognosen für das zukünftige Verkehrsaufkommen benötigt. Auf Autobahnen und Bundesstraßen unterhält die Bundesanstalt für Straßen- und Verkehrswesen (BASt) dazu Dauerzählstellen. Die gewonnenen Daten werden auch online zur Verfügung gestellt, siehe [Jahreswerte hier](https://www.bast.de/DE/Themen/Digitales/HF_1/Massnahmen/verkehrszaehlung/Daten/2023_1/Jawe2023.html). Die Beschreibung der Variablen sind [hier](https://www.bast.de/DE/Themen/Digitales/HF_1/Massnahmen/verkehrszaehlung/pdf-dateien/DZ-Abkuerzungen-Beschreibung.pdf?__blob=publicationFile&v=2) zu finden.

## Aufgabe 1

Erstellen Sie eine Karte des deutschen Autobahnnetzes und stellen Sie in dieser Karte die Verkehrsbelastungen für ein beliebiges Jahr dar.

## Aufgabe 2

Wählen Sie zwei Zählstellen von Autobahnen in einem Ballungsraum und zwei weitere Zählstellen von Autobahnen außerhalb eines Ballungsraumes. Führen Sie für die vier Zählstellen folgende Auswertungen durch:

a) Erstellen Sie für jeden Wochentag eine Ganglinie für eine ausgewählte Zählstelle und stellen Sie diese in einem Diagramm dar.

b) Bestimmen Sie die mittlere werktägliche Verkehrsbelastung (mittlere Stundenwerte dienstags bis
donnerstags, ohne Feiertage und außerhalb der Schulferien) und stellen Sie die Ganglinien "Mittlerer Werktag" für jede Zählstelle in einem Diagramm dar. Erstellen Sie mit denselben Filtern (ohne Feiertage und außerhalb der Schulferien) für jede Zählstelle ein Diagramm für Samstage und Sonntage.

c) Bestimmen Sie die "50. Stunde" der vier Zählstellen und geben das Ergebnis in einer Tabelle aus. Wählen Sie zudem eine geeignete Darstellungsform, um für jede Zählstelle die 50. Stunde im Vergleich zu den restlichen Stunden eines Jahres auszugeben.

d) Untersuchen Sie den prozentualen Anteil des Schwerverkehrs in der Zeitspanne 2003 bis 2018.
Welche Entwicklung / Tendenz lässt sich erkennen?
